name: Go Test Coverage with Coveralls

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21'  # Set this to your Go version

      - name: Run tests with coverage
        run: |
          make test-coverage

      - name: Generate LCOV report
        run: |
          go install github.com/jandelgado/gcov2lcov@latest
          gcov2lcov -infile=network-operator.cover -outfile=coverage.lcov

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
          flag-name: run-flags-1  # Optional: Custom flag name for parallel builds
